#!/usr/bin/env python3
"""Generate shared/conventions-index.md by scanning framework conventions.

Python port of generate-conventions-index.sh. Drops the bash 4+
requirement (the original used associative arrays).

Usage:
  python3 -m shared.generate_conventions_index
"""
from __future__ import annotations

import datetime as dt
import re
import sys
from pathlib import Path

CATEGORIES: list[tuple[str, list[str]]] = [
    ("Error Handling", [
        r"error handl", r"exception.*mapp", r"Error Boundar", r"error propagat",
        r"error message", r"fault toleran",
    ]),
    ("Architecture Boundaries", [
        r"boundary", r"must not import", r"layer.*violat", r"depend.*rule",
        r"core.*adapter", r"adapter.*core", r"cross-module", r"separation of",
    ]),
    ("Naming Conventions", [
        r"naming", r"file naming", r"class naming", r"prefix.*convention",
        r"suffix.*convention", r"camelCase", r"snake_case", r"PascalCase", r"kebab-case",
    ]),
    ("Testing Patterns", [
        r"test.*strateg", r"test.*pattern", r"assert.*quality", r"mock.*only",
        r"fixture", r"test isolat", r"edge case", r"TDD",
    ]),
    ("State Management", [
        r"state manage", r"global state", r"store.*pattern", r"context.*provider",
        r"signal.*store", r"reactive.*state", r"observable.*state",
    ]),
]


def find_matches(conv_path: Path, patterns: list[str]) -> list[tuple[int, str]]:
    """Return [(line_num, content)] for top-3 case-insensitive matches."""
    if not conv_path.is_file():
        return []
    combined = re.compile("|".join(patterns), re.IGNORECASE)
    hits: list[tuple[int, str]] = []
    with conv_path.open(encoding="utf-8", errors="replace") as fh:
        for n, line in enumerate(fh, start=1):
            if combined.search(line):
                hits.append((n, line.rstrip("\n")))
                if len(hits) == 3:
                    break
    return hits


def clean_for_table(text: str) -> str:
    """Strip leading markdown markers, escape pipes, trim to 80 chars."""
    text = re.sub(r"^[#\-* ]+", "", text)
    text = text.replace("|", "∣")
    return text[:80]


def render_index(modules_dir: Path) -> str:
    lines: list[str] = [
        "# Conventions Index",
        "",
        "Auto-generated by `shared/generate_conventions_index.py`. Do not edit manually.",
        "",
        f"Last generated: {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
    ]

    framework_dirs = sorted(p for p in modules_dir.iterdir() if p.is_dir())

    for category, patterns in CATEGORIES:
        lines.extend([
            f"## {category}",
            "",
            "| Framework | Convention | Location |",
            "|-----------|-----------|----------|",
        ])
        for fw_dir in framework_dirs:
            conv = fw_dir / "conventions.md"
            for line_num, content in find_matches(conv, patterns):
                lines.append(f"| {fw_dir.name} | {clean_for_table(content)} | conventions.md:{line_num} |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    plugin_root = Path(__file__).resolve().parents[1]
    modules_dir = plugin_root / "modules" / "frameworks"
    output = plugin_root / "shared" / "conventions-index.md"

    if not modules_dir.is_dir():
        print(f"ERROR: {modules_dir} not found", file=sys.stderr)
        return 1

    output.write_text(render_index(modules_dir), encoding="utf-8")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
