#!/usr/bin/env bash
# Generates shared/conventions-index.md by scanning all framework conventions.
# Requires bash 4.0+ (uses associative arrays). This is a PREFLIGHT script,
# not a hook — the bash 4.0 requirement is acceptable here (same as forge-state.sh).
set -euo pipefail

# Bash 4.0+ guard
if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
  echo "ERROR: generate-conventions-index.sh requires bash 4.0+ (found ${BASH_VERSION})" >&2
  echo "  MacOS: brew install bash" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULES_DIR="$(dirname "$SCRIPT_DIR")/modules/frameworks"
OUTPUT="$SCRIPT_DIR/conventions-index.md"

# Pattern categories to index (grep -i patterns)
declare -A CATEGORIES=(
  ["Error Handling"]="error handl\|exception.*mapp\|Error Boundar\|error propagat\|error message\|fault toleran"
  ["Architecture Boundaries"]="boundary\|must not import\|layer.*violat\|depend.*rule\|core.*adapter\|adapter.*core\|cross-module\|separation of"
  ["Naming Conventions"]="naming\|file naming\|class naming\|prefix.*convention\|suffix.*convention\|camelCase\|snake_case\|PascalCase\|kebab-case"
  ["Testing Patterns"]="test.*strateg\|test.*pattern\|assert.*quality\|mock.*only\|fixture\|test isolat\|edge case\|TDD"
  ["State Management"]="state manage\|global state\|store.*pattern\|context.*provider\|signal.*store\|reactive.*state\|observable.*state"
)

# Ordered category list (bash assoc arrays don't preserve order)
CATEGORY_ORDER=(
  "Error Handling"
  "Architecture Boundaries"
  "Naming Conventions"
  "Testing Patterns"
  "State Management"
)

{
  cat << 'HEADER'
# Conventions Index

Auto-generated by `shared/generate-conventions-index.sh`. Do not edit manually.

HEADER

  echo "Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  for category in "${CATEGORY_ORDER[@]}"; do
    pattern="${CATEGORIES[$category]}"
    echo "## $category"
    echo ""
    echo "| Framework | Convention | Location |"
    echo "|-----------|-----------|----------|"

    for fw_dir in "$MODULES_DIR"/*/; do
      fw=$(basename "$fw_dir")
      conv="$fw_dir/conventions.md"
      [ -f "$conv" ] || continue

      (grep -n -i "$pattern" "$conv" 2>/dev/null || true) | head -3 | while IFS=: read -r line_num line_content; do
        # Clean up the content for table display
        content=$(echo "$line_content" | sed 's/|/∣/g; s/^[#\-\* ]*//' | cut -c 1-80)
        echo "| $fw | $content | conventions.md:$line_num |"
      done
    done

    echo ""
  done
} > "$OUTPUT"

echo "Generated $OUTPUT"
