#!/usr/bin/env python3
"""Generate shared/learnings-index.md from shared/learnings/*.md.

Parses existing PREEMPT-item format (no YAML frontmatter required in source files;
any frontmatter present is silently skipped). Exit codes: 0 success (or --check
match); 1 --check mismatch / missing target; 2 parse error.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

LEARNINGS_DIR = Path("shared/learnings")
OUTPUT_PATH = Path("shared/learnings-index.md")
# Templates, README, and system docs that describe the decay/promotion/discovery
# machinery itself (not PREEMPT corpora) are skipped. They use a different
# heading convention (`# Memory Decay`, `# Rule Promotion Algorithm`, etc.) and
# carry no `### KS-PREEMPT-*` items.
SKIP_FILES = {
    "README.md",
    "_template.md",
    "agent-effectiveness-template.md",
    "decay.md",
    "memory-discovery.md",
    "rule-promotion.md",
}

HEADER_RE = re.compile(r"^#\s+Cross-Project Learnings:\s+(.+?)\s*$")
ITEM_RE = re.compile(r"^###\s+([A-Z0-9\-]+):\s+(.+?)\s*$")
CONFIDENCE_RE = re.compile(r"^-\s+\*\*Confidence:\*\*\s+(HIGH|MEDIUM|LOW)\s*$")
HITS_RE = re.compile(r"^-\s+\*\*Hit count:\*\*\s+(\d+)\s*$")


H1_RE = re.compile(r"^#\s+(.+?)\s*$")


def _normalise_module_name(h1: str, fallback: str) -> str:
    """Extract a module name from any of the H1 conventions in use.

    Recognised forms (in priority order):
      `# Cross-Project Learnings: <name>`
      `# Learnings: <name>`
      `# <name> — Learnings`     (em dash or `--`)
      `# <name>`                  (last resort — used as-is)
    """
    primary = HEADER_RE.match(f"# {h1}")
    if primary:
        return primary.group(1).strip()
    alt = re.match(r"^Learnings:\s+(.+?)\s*$", h1)
    if alt:
        return alt.group(1).strip()
    suffix = re.match(r"^(.+?)\s*[—-]+\s*Learnings\s*$", h1, re.IGNORECASE)
    if suffix:
        return suffix.group(1).strip()
    return h1.strip() or fallback


def _strip_yaml_frontmatter(lines: list[str]) -> list[str]:
    """Remove a leading `---` … `---` YAML frontmatter block, if present.

    The decay frontmatter stamped onto every learnings file; the closing
    fence is followed by the canonical H1. This strips the fenced block so
    downstream regexes never see the embedded `#` comment lines as H1s.
    """
    if not lines or lines[0].strip() != "---":
        return lines
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            return lines[idx + 1:]
    # Unterminated fence — bail out and return the original lines so the
    # caller's `no H1` error fires with the right context.
    return lines


def parse_learning_file(path: Path) -> dict | None:
    """Parse a learning file into a structured dict.

    Returns None for files that have no PREEMPT items (pure module docs).
    Raises ValueError only when no H1 heading is found, which would indicate
    a malformed file.
    """
    content = path.read_text(encoding="utf-8")
    lines = _strip_yaml_frontmatter(content.splitlines())
    raw_h1 = None
    items = []
    current = None
    for line in lines:
        if raw_h1 is None:
            h = H1_RE.match(line)
            if h:
                raw_h1 = h.group(1)
                continue
        i = ITEM_RE.match(line)
        if i:
            if current:
                items.append(current)
            current = {"id": i.group(1), "title": i.group(2), "confidence": "UNKNOWN", "hits": 0}
            continue
        if current:
            c = CONFIDENCE_RE.match(line)
            if c:
                current["confidence"] = c.group(1)
                continue
            h2 = HITS_RE.match(line)
            if h2:
                current["hits"] = int(h2.group(1))
    if current:
        items.append(current)
    if raw_h1 is None:
        raise ValueError(f"{path}: no H1 heading found")
    if not items:
        return None
    module = _normalise_module_name(raw_h1, fallback=path.stem)
    return {"module": module, "path": path, "items": items}


def build_index(learnings_dir: Path) -> str:
    """Build the index markdown (without the timestamp line)."""
    files = sorted(p for p in learnings_dir.glob("*.md") if p.name not in SKIP_FILES)
    entries = []
    for p in files:
        try:
            parsed = parse_learning_file(p)
        except ValueError as e:
            print(f"parse error: {e}", file=sys.stderr)
            sys.exit(2)
        if parsed is not None:
            entries.append(parsed)

    entries.sort(key=lambda e: (e["module"], e["path"].name))

    total_items = sum(len(e["items"]) for e in entries)
    lines = [
        "<!-- GENERATED by scripts/gen-learnings-index.py - DO NOT EDIT BY HAND -->",
        "<!-- Source: shared/learnings/*.md -->",
        "",
        "# Learnings Index",
        "",
        f"{total_items} PREEMPT items across {len(entries)} modules. "
        "Sorted by module, then item ID.",
        "",
    ]
    for e in entries:
        lines.append(f"## {e['module']} ({len(e['items'])})")
        lines.append("")
        lines.append(
            f"Source: [`{e['path'].relative_to(learnings_dir.parent)}`]"
            f"(./{e['path'].relative_to(learnings_dir.parent)})"
        )
        lines.append("")
        if e["items"]:
            lines.append("| ID | Title | Confidence | Hits |")
            lines.append("|----|-------|------------|------|")
            for item in e["items"]:
                title = item["title"].replace("|", "\\|")
                lines.append(
                    f"| {item['id']} | {title} | {item['confidence']} | {item['hits']} |"
                )
        else:
            lines.append("_No PREEMPT items yet._")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def content_hash(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    parser.add_argument("--output", default=str(OUTPUT_PATH))
    args = parser.parse_args()

    body = build_index(LEARNINGS_DIR)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header_timestamp_line = f"<!-- Last generated: {timestamp} -->\n"

    output_path = Path(args.output)
    if args.check:
        if not output_path.exists():
            print(
                f"{output_path} missing; run scripts/gen-learnings-index.py",
                file=sys.stderr,
            )
            return 1
        existing = output_path.read_text(encoding="utf-8")
        existing_body = "\n".join(
            line
            for line in existing.splitlines()
            if not line.startswith("<!-- Last generated:")
        ).rstrip() + "\n"
        if content_hash(existing_body) != content_hash(body):
            print(
                "learnings-index is stale; run scripts/gen-learnings-index.py",
                file=sys.stderr,
            )
            return 1
        return 0

    lines = body.splitlines()
    out = [lines[0], lines[1], header_timestamp_line.rstrip()] + lines[2:]
    output_path.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
