#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# enrich-symbols.sh — Symbol-Level Graph Enrichment
#
# Extracts class, interface, struct, trait, and function definitions from
# specific files using regex and outputs Cypher for symbol-level nodes.
#
# Usage:
#   ./shared/graph/enrich-symbols.sh --project-root /path/to/project [--project-id org/repo] [--component api] [--files "a.kt,b.ts"] file1.kt file2.ts
#
# Output: Cypher to stdout
# Side effects:
#   - Appends enriched file paths to .forge/graph/.enriched-files
# ============================================================================

PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=../platform.sh
source "${PLUGIN_ROOT}/shared/platform.sh"

# Requires Bash 4.0+ (uses associative arrays)
require_bash4 "enrich-symbols.sh" || exit 1

PROJECT_ROOT=""
PROJECT_ID=""
COMPONENT=""
FILES_FILTER=""
declare -a FILES=()

# --- Argument parsing ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --project-id)
      PROJECT_ID="$2"
      shift 2
      ;;
    --component)
      COMPONENT="$2"
      shift 2
      ;;
    --files)
      FILES_FILTER="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      echo "Usage: enrich-symbols.sh --project-root /path/to/project [--project-id org/repo] [--component api] file1 file2 ..." >&2
      exit 1
      ;;
    *)
      FILES+=("$1")
      shift
      ;;
  esac
done

if [[ -z "$PROJECT_ROOT" ]]; then
  echo "Error: --project-root is required" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"

# Auto-derive project_id if not provided
if [[ -z "${PROJECT_ID:-}" ]]; then
  PROJECT_ID=$(derive_project_id "$PROJECT_ROOT")
fi
COMPONENT="${COMPONENT:-}"

# Cypher-safe component value
if [[ -n "$COMPONENT" ]]; then
  COMPONENT_CYPHER="'${COMPONENT}'"
else
  COMPONENT_CYPHER="null"
fi

# If --files provided (comma-separated), add to FILES array
if [[ -n "$FILES_FILTER" ]]; then
  IFS=',' read -ra filter_arr <<< "$FILES_FILTER"
  for f in "${filter_arr[@]}"; do
    f=$(echo "$f" | xargs)  # trim whitespace
    [[ -n "$f" ]] && FILES+=("$f")
  done
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "Error: at least one file argument is required (positional or --files)" >&2
  exit 1
fi

# --- Ensure output directories ---
GRAPH_DIR="${PROJECT_ROOT}/.forge/graph"
mkdir -p "$GRAPH_DIR"
ENRICHED_FILE="${GRAPH_DIR}/.enriched-files"

# --- Helper: escape strings for Cypher ---
cypher_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\'/\\\'}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/}"
  printf '%s' "$s"
}

# --- Helper: determine language from extension ---
ext_to_lang() {
  local file="$1"
  case "$file" in
    *.kt)        echo "kotlin" ;;
    *.java)      echo "java" ;;
    *.ts|*.tsx)  echo "typescript" ;;
    *.js|*.jsx)  echo "javascript" ;;
    *.py)        echo "python" ;;
    *.go)        echo "go" ;;
    *.rs)        echo "rust" ;;
    *.rb)        echo "ruby" ;;
    *.php)       echo "php" ;;
    *.ex|*.exs)  echo "elixir" ;;
    *.scala)     echo "scala" ;;
    *.dart)      echo "dart" ;;
    *.swift)     echo "swift" ;;
    *.cs)        echo "csharp" ;;
    *.c|*.h)     echo "c" ;;
    *.cpp|*.hpp) echo "cpp" ;;
    *)           echo "unknown" ;;
  esac
}

# ============================================================================
# Emit header
# ============================================================================

echo "// ===================================="
echo "// Symbol-Level Graph Enrichment"
echo "// Generated by enrich-symbols.sh"
echo "// Project: ${PROJECT_ROOT}"
echo "// Files: ${#FILES[@]}"
echo "// ===================================="
echo ""

# ============================================================================
# Language-specific extraction functions
#
# Each extract_* function reads the file and emits Cypher for:
#   - ProjectClass nodes (classes, interfaces, structs, traits, objects, modules)
#   - CLASS_IN_FILE edges
#   - EXTENDS_CLASS edges (where detectable)
#   - ProjectFunction nodes
# ============================================================================

extract_kotlin() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes, data classes, objects, interfaces
  grep -nE '^\s*(data\s+)?class\s+\w+|^\s*interface\s+\w+|^\s*object\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info
    if echo "$line" | grep -qE '^\s*[0-9]+:\s*(data\s+)?class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(data\s+)?class\s+(\w+).*/\2/')"
      kind="class"
      # Check for extends: class Foo : Bar or class Foo(val x: X) : Bar
      parent_info="$(echo "$line" | sed -E 's/^[^:]*:\s*(data\s+)?class\s+\w+[^:]*:\s*//' | grep -oE '^\w+' || true)"
    elif echo "$line" | grep -qE '^\s*[0-9]+:\s*interface\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*interface\s+(\w+).*/\1/')"
      kind="interface"
      parent_info=""
    elif echo "$line" | grep -qE '^\s*[0-9]+:\s*object\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*object\s+(\w+).*/\1/')"
      kind="object"
      parent_info="$(echo "$line" | sed -E 's/^[^:]*:\s*object\s+\w+[^:]*:\s*//' | grep -oE '^\w+' || true)"
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" && "$parent_info" != "$name" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions
  grep -nE '^\s*(override\s+)?fun\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(override\s+)?fun\s+(\w+).*/\2/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_java() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and interfaces
  grep -nE '^\s*(public\s+)?(abstract\s+)?class\s+\w+|^\s*(public\s+)?interface\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info
    if echo "$line" | grep -qE 'class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*class\s+(\w+).*/\1/')"
      kind="class"
      # Check extends
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
      # Check implements
      local impl_info
      impl_info="$(echo "$line" | grep -oE 'implements\s+\w+' | sed 's/implements\s*//' || true)"
    elif echo "$line" | grep -qE 'interface\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*interface\s+(\w+).*/\1/')"
      kind="interface"
      parent_info=""
      local impl_info=""
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
      if [[ -n "${impl_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$impl_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Methods — match public/private/protected return_type methodName(
  grep -nE '^\s*(public|private|protected)?\s*(static\s+)?\w+\s+\w+\s*\(' "$abs_path" 2>/dev/null | \
    grep -vE '^\s*[0-9]+:\s*(if|for|while|switch|catch|return|new|import|package)\s' | while IFS= read -r line; do
      local fname
      fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(public\s+|private\s+|protected\s+)?(static\s+)?(\w+\s+)?(\w+)\s*\(.*/\4/')"
      # Skip constructors (name matches class pattern — starts with uppercase, but we emit anyway)
      if [[ -n "$fname" && "$fname" != "class" && "$fname" != "interface" ]]; then
        echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      fi
    done
}

extract_typescript() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and interfaces
  grep -nE '^\s*(export\s+)?(abstract\s+)?class\s+\w+|^\s*(export\s+)?interface\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info impl_info
    if echo "$line" | grep -qE 'class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*class\s+(\w+).*/\1/')"
      kind="class"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
      impl_info="$(echo "$line" | grep -oE 'implements\s+\w+' | sed 's/implements\s*//' || true)"
    elif echo "$line" | grep -qE 'interface\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*interface\s+(\w+).*/\1/')"
      kind="interface"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
      impl_info=""
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
      if [[ -n "${impl_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$impl_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Top-level and exported functions
  grep -nE '^\s*(export\s+)?(async\s+)?function\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(export\s+)?(async\s+)?function\s+(\w+).*/\3/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_python() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes with optional parents
  grep -nE '^\s*class\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name parent_info
    name="$(echo "$line" | sed -E 's/^[0-9]+:\s*class\s+(\w+).*/\1/')"
    # Extract parent class from class Foo(Bar):
    parent_info="$(echo "$line" | grep -oE 'class\s+\w+\(\s*\w+' | sed -E 's/class\s+\w+\(\s*//' || true)"

    if [[ -n "$name" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: 'class', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" && "$parent_info" != "object" && "$parent_info" != "$name" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions (including async def)
  grep -nE '^\s*(async\s+)?def\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(async\s+)?def\s+(\w+).*/\2/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_go() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Structs and interfaces
  grep -nE '^\s*type\s+\w+\s+(struct|interface)' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind
    name="$(echo "$line" | sed -E 's/^[0-9]+:\s*type\s+(\w+)\s+(struct|interface).*/\1/')"
    kind="$(echo "$line" | sed -E 's/^[0-9]+:\s*type\s+\w+\s+(struct|interface).*/\1/')"

    if [[ -n "$name" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
    fi
  done

  # Functions (both standalone and methods)
  grep -nE '^\s*func\s+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    # Method: func (r *Receiver) MethodName(...)
    if echo "$line" | grep -qE '^\s*[0-9]+:\s*func\s+\('; then
      fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*func\s+\([^)]+\)\s+(\w+).*/\1/')"
    else
      # Standalone: func FuncName(...)
      fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*func\s+(\w+).*/\1/')"
    fi
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_rust() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Structs, traits
  grep -nE '^\s*(pub\s+)?struct\s+\w+|^\s*(pub\s+)?trait\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind
    if echo "$line" | grep -qE 'struct\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(pub\s+)?struct\s+(\w+).*/\2/')"
      kind="struct"
    elif echo "$line" | grep -qE 'trait\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(pub\s+)?trait\s+(\w+).*/\2/')"
      kind="trait"
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
    fi
  done

  # impl blocks — impl Trait for Struct
  grep -nE '^\s*impl\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    if echo "$line" | grep -qE 'impl\s+\w+\s+for\s+\w+'; then
      local trait_name struct_name
      trait_name="$(echo "$line" | sed -E 's/^[0-9]+:\s*impl\s+(\w+)\s+for\s+(\w+).*/\1/')"
      struct_name="$(echo "$line" | sed -E 's/^[0-9]+:\s*impl\s+(\w+)\s+for\s+(\w+).*/\2/')"
      if [[ -n "$trait_name" && -n "$struct_name" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$struct_name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$trait_name")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions
  grep -nE '^\s*(pub\s+)?(async\s+)?fn\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(pub\s+)?(async\s+)?fn\s+(\w+).*/\3/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_ruby() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and modules
  grep -nE '^\s*class\s+\w+|^\s*module\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info=""
    if echo "$line" | grep -qE 'class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*class\s+(\w+).*/\1/')"
      kind="class"
      # Check for < inheritance
      parent_info="$(echo "$line" | grep -oE '<\s*\w+' | sed 's/<\s*//' || true)"
    elif echo "$line" | grep -qE 'module\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*module\s+(\w+).*/\1/')"
      kind="module"
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Methods
  grep -nE '^\s*def\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*def\s+(\w+).*/\1/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_php() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and interfaces
  grep -nE '^\s*(abstract\s+)?class\s+\w+|^\s*interface\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info impl_info
    if echo "$line" | grep -qE 'class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(abstract\s+)?class\s+(\w+).*/\2/')"
      kind="class"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
      impl_info="$(echo "$line" | grep -oE 'implements\s+\w+' | sed 's/implements\s*//' || true)"
    elif echo "$line" | grep -qE 'interface\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*interface\s+(\w+).*/\1/')"
      kind="interface"
      parent_info=""
      impl_info=""
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
      if [[ -n "${impl_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$impl_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions
  grep -nE '^\s*(public|private|protected)?\s*(static\s+)?function\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(public\s+|private\s+|protected\s+)?(static\s+)?function\s+(\w+).*/\3/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_csharp() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and interfaces
  grep -nE '^\s*(public\s+)?(abstract\s+)?class\s+\w+|^\s*(public\s+)?interface\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info
    if echo "$line" | grep -qE 'class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*class\s+(\w+).*/\1/')"
      kind="class"
      # C# uses : for inheritance
      parent_info="$(echo "$line" | grep -oE ':\s*\w+' | head -1 | sed 's/:\s*//' || true)"
    elif echo "$line" | grep -qE 'interface\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:.*interface\s+(\w+).*/\1/')"
      kind="interface"
      parent_info=""
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Methods
  grep -nE '^\s*(public|private|protected|internal)?\s*(static\s+)?(async\s+)?\w+\s+\w+\s*\(' "$abs_path" 2>/dev/null | \
    grep -vE '^\s*[0-9]+:\s*(if|for|while|switch|catch|return|new|using|namespace)\s' | while IFS= read -r line; do
      local fname
      fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(public\s+|private\s+|protected\s+|internal\s+)?(static\s+)?(async\s+)?(override\s+)?(\w+\s+)?(\w+)\s*\(.*/\6/')"
      if [[ -n "$fname" && "$fname" != "class" && "$fname" != "interface" ]]; then
        echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      fi
    done
}

extract_swift() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes, structs, protocols
  grep -nE '^\s*(class|struct|protocol)\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info=""
    kind="$(echo "$line" | sed -E 's/^[0-9]+:\s*(class|struct|protocol)\s+.*/\1/')"
    name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(class|struct|protocol)\s+(\w+).*/\2/')"
    # Check for : inheritance
    if [[ "$kind" == "class" || "$kind" == "struct" ]]; then
      parent_info="$(echo "$line" | grep -oE ':\s*\w+' | head -1 | sed 's/:\s*//' || true)"
    fi

    if [[ -n "$name" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" && "$parent_info" != "$name" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions
  grep -nE '^\s*(override\s+)?(static\s+)?func\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(override\s+)?(static\s+)?func\s+(\w+).*/\3/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_elixir() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Modules
  grep -nE '^\s*defmodule\s+\S+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name
    name="$(echo "$line" | sed -E 's/^[0-9]+:\s*defmodule\s+(\S+)\s*.*/\1/')"
    if [[ -n "$name" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: 'module', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
    fi
  done

  # Functions
  grep -nE '^\s*def[p]?\s+\w+' "$abs_path" 2>/dev/null | \
    grep -vE 'defmodule|defstruct|defmacro|defimpl|defprotocol|defoverridable|defdelegate' | while IFS= read -r line; do
      local fname
      fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*def[p]?\s+(\w+).*/\1/')"
      if [[ -n "$fname" ]]; then
        echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      fi
    done
}

extract_scala() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes, case classes, traits, objects
  grep -nE '^\s*(case\s+)?class\s+\w+|^\s*trait\s+\w+|^\s*object\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name kind parent_info=""
    if echo "$line" | grep -qE '(case\s+)?class\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(case\s+)?class\s+(\w+).*/\2/')"
      kind="class"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
    elif echo "$line" | grep -qE 'trait\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*trait\s+(\w+).*/\1/')"
      kind="trait"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
    elif echo "$line" | grep -qE 'object\s+'; then
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*object\s+(\w+).*/\1/')"
      kind="object"
      parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
    fi

    if [[ -n "${name:-}" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done

  # Functions
  grep -nE '^\s*(override\s+)?def\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local fname
    fname="$(echo "$line" | sed -E 's/^[0-9]+:\s*(override\s+)?def\s+(\w+).*/\2/')"
    if [[ -n "$fname" ]]; then
      echo "MERGE (:ProjectFunction {name: '$(cypher_escape "$fname")', file_path: '${esc_path}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
    fi
  done
}

extract_c_cpp() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes and structs
  grep -nE '^\s*(class|struct)\s+\w+' "$abs_path" 2>/dev/null | \
    grep -vE '^\s*[0-9]+:\s*(class|struct)\s+\w+\s*;' | while IFS= read -r line; do
      local name kind parent_info=""
      kind="$(echo "$line" | sed -E 's/^[0-9]+:\s*(class|struct)\s+.*/\1/')"
      name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(class|struct)\s+(\w+).*/\2/')"
      # Check for : public Base
      parent_info="$(echo "$line" | grep -oE ':\s*(public|protected|private)\s+\w+' | sed -E 's/:\s*(public|protected|private)\s+//' || true)"

      if [[ -n "$name" ]]; then
        echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: '${kind}', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
        echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
        if [[ -n "${parent_info:-}" ]]; then
          echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
        fi
      fi
    done
}

extract_dart() {
  local file="$1" abs_path="$2"
  local esc_path
  esc_path="$(cypher_escape "$file")"

  # Classes (with optional abstract)
  grep -nE '^\s*(abstract\s+)?class\s+\w+' "$abs_path" 2>/dev/null | while IFS= read -r line; do
    local name parent_info
    name="$(echo "$line" | sed -E 's/^[0-9]+:\s*(abstract\s+)?class\s+(\w+).*/\2/')"
    parent_info="$(echo "$line" | grep -oE 'extends\s+\w+' | sed 's/extends\s*//' || true)"
    local impl_info
    impl_info="$(echo "$line" | grep -oE 'implements\s+\w+' | sed 's/implements\s*//' || true)"

    if [[ -n "$name" ]]; then
      echo "MERGE (:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', kind: 'class', project_id: '${PROJECT_ID}', component: ${COMPONENT_CYPHER}});"
      echo "MATCH (c:ProjectClass {name: '$(cypher_escape "$name")', file_path: '${esc_path}', project_id: '${PROJECT_ID}'}), (f:ProjectFile {path: '${esc_path}', project_id: '${PROJECT_ID}'}) CREATE (c)-[:CLASS_IN_FILE]->(f);"
      if [[ -n "${parent_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$parent_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
      if [[ -n "${impl_info:-}" ]]; then
        echo "MATCH (a:ProjectClass {name: '$(cypher_escape "$name")', project_id: '${PROJECT_ID}'}), (b:ProjectClass {name: '$(cypher_escape "$impl_info")', project_id: '${PROJECT_ID}'}) CREATE (a)-[:EXTENDS_CLASS]->(b);"
      fi
    fi
  done
}

# ============================================================================
# Process each file
# ============================================================================

FILE_COUNT=0

for file in "${FILES[@]}"; do
  # Resolve to relative path within project
  local_path="$file"
  # If absolute, make relative
  if [[ "$local_path" == /* ]]; then
    local_path="${local_path#${PROJECT_ROOT}/}"
  fi

  abs_path="${PROJECT_ROOT}/${local_path}"

  if [[ ! -f "$abs_path" ]]; then
    echo "// Skipping ${local_path} — file not found" >&2
    continue
  fi

  lang="$(ext_to_lang "$local_path")"
  if [[ "$lang" == "unknown" ]]; then
    echo "// Skipping ${local_path} — unsupported language" >&2
    continue
  fi

  echo "// --- ${local_path} (${lang}) ---"

  case "$lang" in
    kotlin)               extract_kotlin "$local_path" "$abs_path" ;;
    java)                 extract_java "$local_path" "$abs_path" ;;
    typescript|javascript) extract_typescript "$local_path" "$abs_path" ;;
    python)               extract_python "$local_path" "$abs_path" ;;
    go)                   extract_go "$local_path" "$abs_path" ;;
    rust)                 extract_rust "$local_path" "$abs_path" ;;
    ruby)                 extract_ruby "$local_path" "$abs_path" ;;
    php)                  extract_php "$local_path" "$abs_path" ;;
    csharp)               extract_csharp "$local_path" "$abs_path" ;;
    swift)                extract_swift "$local_path" "$abs_path" ;;
    elixir)               extract_elixir "$local_path" "$abs_path" ;;
    scala)                extract_scala "$local_path" "$abs_path" ;;
    c|cpp)                extract_c_cpp "$local_path" "$abs_path" ;;
    dart)                 extract_dart "$local_path" "$abs_path" ;;
  esac

  echo ""

  # Record enrichment
  echo "$local_path" >> "$ENRICHED_FILE"
  ((FILE_COUNT++)) || true
done

echo "// --- Enrichment Complete ---"
echo "// Files enriched: ${FILE_COUNT}"
