#!/usr/bin/env bash
set -euo pipefail

# Requires Bash 4.0+ (uses associative arrays)
if (( BASH_VERSINFO[0] < 4 )); then
  echo "[generate-seed] Bash 4.0+ required (found ${BASH_VERSION}). Cannot generate seed." >&2
  exit 1
fi

# ============================================================================
# generate-seed.sh — Plugin Knowledge Graph Seed Generator
#
# Scans the plugin's module structure and outputs valid Cypher statements
# that represent the entire plugin's module relationship graph.
#
# Usage:
#   ./shared/graph/generate-seed.sh              # writes to shared/graph/seed.cypher
#   ./shared/graph/generate-seed.sh --dry-run    # prints to stdout only
# ============================================================================

PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUTPUT_FILE="${PLUGIN_ROOT}/shared/graph/seed.cypher"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# documentation and code-quality layers included so Step 5/6 auto-create LayerModule and FrameworkBinding nodes
LAYERS=(databases persistence migrations api-protocols messaging caching search storage auth observability build-systems ci-cd container-orchestration documentation code-quality)
BINDING_LAYERS=("${LAYERS[@]}" testing)

# --- JSON parsing helper ---
# Uses python3 for JSON parsing (warns on failure, returns empty)
json_parse() {
  python3 -c "$1" 2>/dev/null || {
    echo "[generate-seed] Warning: Python parsing failed" >&2
    return 0
  }
}

# --- Output buffer ---
CYPHER=""

emit() {
  CYPHER+="$1"$'\n'
}

emit_blank() {
  CYPHER+=$'\n'
}

# ============================================================================
# Header
# ============================================================================
emit "// ============================"
emit "// Plugin Knowledge Graph Seed"
emit "// Generated by generate-seed.sh"
emit "// ============================"
emit_blank

# ============================================================================
# Step 0: Indexes
# ============================================================================
emit "// --- Indexes ---"
emit "CREATE INDEX IF NOT EXISTS FOR (f:Framework) ON (f.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (l:Language) ON (l.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (t:TestingFramework) ON (t.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (m:LayerModule) ON (m.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (a:Agent) ON (a.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (c:SharedContract) ON (c.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (pf:ProjectFile) ON (pf.path);"
emit "CREATE INDEX IF NOT EXISTS FOR (pc:ProjectClass) ON (pc.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (pd:ProjectDependency) ON (pd.name);"
emit "CREATE INDEX IF NOT EXISTS FOR (pp:ProjectPackage) ON (pp.path);"
emit "CREATE INDEX IF NOT EXISTS FOR (df:DocFile) ON (df.path);"
emit "CREATE INDEX IF NOT EXISTS FOR (ds:DocSection) ON (ds.file_path);"
emit "CREATE INDEX IF NOT EXISTS FOR (dd:DocDecision) ON (dd.id);"
emit "CREATE INDEX IF NOT EXISTS FOR (dc:DocConstraint) ON (dc.id);"
emit "CREATE INDEX IF NOT EXISTS FOR (dg:DocDiagram) ON (dg.path);"
emit_blank

# ============================================================================
# Step 1: Languages
# ============================================================================
emit "// --- Languages ---"
for f in "${PLUGIN_ROOT}"/modules/languages/*.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f" .md)"
  rel="modules/languages/${name}.md"
  emit "CREATE (:Language {name: '${name}', file_path: '${rel}'});"
done
emit_blank

# ============================================================================
# Step 2: Frameworks
# ============================================================================
emit "// --- Frameworks ---"
for f in "${PLUGIN_ROOT}"/modules/frameworks/*/conventions.md; do
  [[ -e "$f" ]] || continue
  fw_dir="$(dirname "$f")"
  name="$(basename "$fw_dir")"
  rel="modules/frameworks/${name}/conventions.md"
  emit "CREATE (:Framework {name: '${name}', file_path: '${rel}'});"
done
emit_blank

# ============================================================================
# Step 3: Variants (Framework -> Language HAS_VARIANT edges)
# ============================================================================
emit "// --- Variants ---"
for f in "${PLUGIN_ROOT}"/modules/frameworks/*/variants/*.md; do
  [[ -e "$f" ]] || continue
  lang="$(basename "$f" .md)"
  fw_dir="$(dirname "$(dirname "$f")")"
  fw="$(basename "$fw_dir")"
  emit "MATCH (f:Framework {name: '${fw}'}), (l:Language {name: '${lang}'}) CREATE (f)-[:HAS_VARIANT]->(l);"
done
emit_blank

# ============================================================================
# Step 4: Testing Frameworks
# ============================================================================
emit "// --- Testing Frameworks ---"
for f in "${PLUGIN_ROOT}"/modules/testing/*.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f" .md)"
  rel="modules/testing/${name}.md"
  emit "CREATE (:TestingFramework {name: '${name}', file_path: '${rel}'});"
done
emit_blank

# ============================================================================
# Step 5: Layer Modules
# ============================================================================
emit "// --- Layer Modules ---"
for layer in "${LAYERS[@]}"; do
  for f in "${PLUGIN_ROOT}/modules/${layer}"/*.md; do
    [[ -e "$f" ]] || continue
    name="$(basename "$f" .md)"
    rel="modules/${layer}/${name}.md"
    emit "CREATE (:LayerModule {name: '${name}', layer: '${layer}', file_path: '${rel}'});"
  done
done
emit_blank

# ============================================================================
# Step 6: Framework Bindings
# ============================================================================
emit "// --- Framework Bindings ---"
for fw_dir in "${PLUGIN_ROOT}"/modules/frameworks/*/; do
  [[ -d "$fw_dir" ]] || continue
  fw="$(basename "$fw_dir")"
  for layer in "${BINDING_LAYERS[@]}"; do
    layer_dir="${fw_dir}${layer}"
    [[ -d "$layer_dir" ]] || continue
    for f in "${layer_dir}"/*.md; do
      [[ -e "$f" ]] || continue
      module_name="$(basename "$f" .md)"
      binding_name="${fw}-${module_name}"
      rel="modules/frameworks/${fw}/${layer}/${module_name}.md"

      if [[ "$layer" == "testing" ]]; then
        # Testing bindings: PAIRS_WITH edge (no FrameworkBinding node, just the edge)
        emit "MATCH (f:Framework {name: '${fw}'}), (t:TestingFramework {name: '${module_name}'}) CREATE (f)-[:PAIRS_WITH]->(t);"
      else
        # Non-testing bindings: FrameworkBinding node + EXTENDS + HAS_BINDING edges
        emit "CREATE (:FrameworkBinding {name: '${binding_name}', framework: '${fw}', layer: '${layer}', file_path: '${rel}'});"
        emit "MATCH (b:FrameworkBinding {name: '${binding_name}'}), (m:LayerModule {name: '${module_name}'}) CREATE (b)-[:EXTENDS]->(m);"
        emit "MATCH (f:Framework {name: '${fw}'}), (b:FrameworkBinding {name: '${binding_name}'}) CREATE (f)-[:HAS_BINDING]->(b);"
      fi
    done
  done
done
emit_blank

# ============================================================================
# Step 7: Agents
# ============================================================================
emit "// --- Agents ---"

# Collect all agent names first (for DISPATCHES matching)
declare -a AGENT_NAMES=()
for f in "${PLUGIN_ROOT}"/agents/*.md; do
  [[ -e "$f" ]] || continue
  AGENT_NAMES+=("$(basename "$f" .md)")
done

for f in "${PLUGIN_ROOT}"/agents/*.md; do
  [[ -e "$f" ]] || continue
  # Parse YAML frontmatter for name
  agent_name="$(basename "$f" .md)"
  rel="agents/${agent_name}.md"

  # Determine role
  role="other"
  if [[ "$agent_name" == "pl-100-orchestrator" ]]; then
    role="orchestrator"
  elif [[ "$agent_name" == *"-reviewer" ]]; then
    role="reviewer"
  elif [[ "$agent_name" == pl-* ]]; then
    role="pipeline"
  fi

  # Determine label (Reviewer agents get dual label)
  if [[ "$role" == "reviewer" ]]; then
    emit "CREATE (:Agent:Reviewer {name: '${agent_name}', role: '${role}', file_path: '${rel}'});"
  else
    emit "CREATE (:Agent {name: '${agent_name}', role: '${role}', file_path: '${rel}'});"
  fi
done
emit_blank

# Shared temp file for agent body extraction (avoids pipe buffer limits on large agents >64KB)
_body_tmp="$(mktemp)"
trap 'rm -f "$_body_tmp"' EXIT

# DISPATCHES edges (best-effort: look for agent names referenced in files with Agent tool)
emit "// --- Agent DISPATCHES edges ---"
for f in "${PLUGIN_ROOT}"/agents/*.md; do
  [[ -e "$f" ]] || continue
  agent_name="$(basename "$f" .md)"

  # Only check files that have Agent in their tools list
  has_agent_tool=$(sed -n '/^---$/,/^---$/p' "$f" | grep -q 'Agent' && echo "yes" || echo "no")
  [[ "$has_agent_tool" == "yes" ]] || continue

  # Get the body (after second ---) — write to temp file to avoid pipe buffer limits on large agents
  sed '1,/^---$/d; 1,/^---$/d' "$f" > "$_body_tmp"

  for target in "${AGENT_NAMES[@]}"; do
    [[ "$target" == "$agent_name" ]] && continue
    if grep -q "$target" "$_body_tmp"; then
      emit "MATCH (a:Agent {name: '${agent_name}'}), (b:Agent {name: '${target}'}) CREATE (a)-[:DISPATCHES]->(b);"
    fi
  done
done
emit_blank

# ============================================================================
# Step 8: Shared Contracts
# ============================================================================
emit "// --- Shared Contracts ---"
for f in "${PLUGIN_ROOT}"/shared/*.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f" .md)"
  rel="shared/${name}.md"
  emit "CREATE (:SharedContract {name: '${name}', file_path: '${rel}'});"
done
emit_blank

# ============================================================================
# Step 8b: Agent READS SharedContract edges
# ============================================================================
emit "// --- Agent READS SharedContract edges ---"
# Collect shared contract names
declare -a CONTRACT_NAMES=()
for f in "${PLUGIN_ROOT}"/shared/*.md; do
  [[ -e "$f" ]] || continue
  CONTRACT_NAMES+=("$(basename "$f" .md)")
done

for f in "${PLUGIN_ROOT}"/agents/*.md; do
  [[ -e "$f" ]] || continue
  agent_name="$(basename "$f" .md)"
  # Get body after frontmatter — write to temp file to avoid pipe buffer limits on large agents (>64KB)
  sed '1,/^---$/d; 1,/^---$/d' "$f" > "$_body_tmp"

  for contract in "${CONTRACT_NAMES[@]}"; do
    # Check if agent body references the contract file (backtick-quoted, path-qualified, or .md suffix)
    if grep -qE "(shared/|[\`'\"])${contract}(\.md|[\`'\"])" "$_body_tmp" 2>/dev/null; then
      emit "MATCH (a:Agent {name: '${agent_name}'}), (c:SharedContract {name: '${contract}'}) CREATE (a)-[:READS]->(c);"
    fi
  done
done
emit_blank

# ============================================================================
# Step 9: Check Rules (from rules-override.json)
# ============================================================================
emit "// --- Check Rules ---"
for f in "${PLUGIN_ROOT}"/modules/frameworks/*/rules-override.json; do
  [[ -e "$f" ]] || continue
  fw_dir="$(dirname "$f")"
  fw="$(basename "$fw_dir")"
  rel="modules/frameworks/${fw}/rules-override.json"

  # Extract all rule IDs from all locations in the JSON, skipping disabled
  rule_ids="$(json_parse "
import json, sys
data = json.load(open('${f}'))
ids = set()
# additional_rules at top level
for r in data.get('additional_rules', []):
    if 'id' in r and not r.get('disabled'):
        ids.add(r['id'])
# shared_rules.additional_rules
for r in data.get('shared_rules', {}).get('additional_rules', []):
    if 'id' in r and not r.get('disabled'):
        ids.add(r['id'])
# variant_rules.*.additional_rules
for vk, vv in data.get('variant_rules', {}).items():
    for r in vv.get('additional_rules', []):
        if 'id' in r and not r.get('disabled'):
            ids.add(r['id'])
for rid in sorted(ids):
    print(rid)
")"

  for rule_id in $rule_ids; do
    emit "CREATE (:CheckRule {id: '${rule_id}', file_path: '${rel}'});"
    emit "MATCH (b:FrameworkBinding), (r:CheckRule {id: '${rule_id}'}) WHERE b.framework = '${fw}' CREATE (b)-[:OVERRIDES_RULE]->(r);"
  done
done
emit_blank

# ============================================================================
# Step 10: Learnings
# ============================================================================
emit "// --- Learnings ---"
for f in "${PLUGIN_ROOT}"/shared/learnings/*.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f" .md)"
  rel="shared/learnings/${name}.md"
  emit "CREATE (:Learnings {name: '${name}', file_path: '${rel}'});"
done
emit_blank

emit "// --- Learnings edges ---"
for f in "${PLUGIN_ROOT}"/shared/learnings/*.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f" .md)"
  # Try to match to LayerModule, TestingFramework, Language, or Framework
  emit "MATCH (l:Learnings {name: '${name}'}), (m:LayerModule {name: '${name}'}) CREATE (m)-[:HAS_LEARNINGS]->(l);"
  emit "MATCH (l:Learnings {name: '${name}'}), (t:TestingFramework {name: '${name}'}) CREATE (t)-[:HAS_LEARNINGS]->(l);"
  emit "MATCH (l:Learnings {name: '${name}'}), (la:Language {name: '${name}'}) CREATE (la)-[:HAS_LEARNINGS]->(l);"
  emit "MATCH (l:Learnings {name: '${name}'}), (f:Framework {name: '${name}'}) CREATE (f)-[:HAS_LEARNINGS]->(l);"
done
emit_blank

# ============================================================================
# Step 11: Canonical Pairings
# ============================================================================
emit "// --- Canonical Pairings ---"
PAIRINGS_FILE="${PLUGIN_ROOT}/shared/graph/canonical-pairings.json"
if [[ -f "$PAIRINGS_FILE" ]]; then
  # canonical_testing
  while IFS= read -r line; do
    emit "$line"
  done < <(json_parse "
import json
data = json.load(open('${PAIRINGS_FILE}'))
for lang, test in sorted(data.get('canonical_testing', {}).items()):
    print(f\"MATCH (l:Language {{name: '{lang}'}}), (t:TestingFramework {{name: '{test}'}}) CREATE (l)-[:CANONICAL_TESTING]->(t);\")
")

  # canonical_persistence
  while IFS= read -r line; do
    emit "$line"
  done < <(json_parse "
import json
data = json.load(open('${PAIRINGS_FILE}'))
for lang, mod in sorted(data.get('canonical_persistence', {}).items()):
    print(f\"MATCH (l:Language {{name: '{lang}'}}), (m:LayerModule {{name: '{mod}'}}) CREATE (l)-[:CANONICAL_PERSISTENCE]->(m);\")
")
fi
emit_blank

# ============================================================================
# Step 12: Seed Marker (for idempotent import detection)
# ============================================================================
emit "// --- Seed Marker ---"
emit "CREATE (:_SeedMarker {id: 'dev-pipeline-seed-v2'});"
emit_blank

# ============================================================================
# Output
# ============================================================================
if [[ "$DRY_RUN" == true ]]; then
  printf '%s' "$CYPHER"
else
  printf '%s' "$CYPHER" > "$OUTPUT_FILE"
  echo "Seed written to ${OUTPUT_FILE}"
  echo "CREATE count: $(echo "$CYPHER" | grep -c 'CREATE')"
  echo "MATCH count:  $(echo "$CYPHER" | grep -c 'MATCH')"
fi
