#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# update-project-graph.sh — Incremental Project Graph Update
#
# Updates the graph for specific changed files instead of full rebuild.
# Used by the orchestrator at stage boundaries (post-IMPLEMENT, post-VERIFY,
# pre-REVIEW).
#
# Usage:
#   ./shared/graph/update-project-graph.sh \
#     --project-root /path/to/project \
#     [--project-id org/repo] \
#     [--component api] \
#     --files "src/Main.kt,src/Service.kt" \
#     [--deleted "src/OldFile.kt"]
#
# Output: Cypher to stdout
# ============================================================================

PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=../platform.sh
source "${PLUGIN_ROOT}/shared/platform.sh"

PROJECT_ROOT=""
PROJECT_ID=""
COMPONENT=""
CHANGED_FILES=""
DELETED_FILES=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root) PROJECT_ROOT="$2"; shift 2 ;;
    --project-id)   PROJECT_ID="$2"; shift 2 ;;
    --component)    COMPONENT="$2"; shift 2 ;;
    --files)        CHANGED_FILES="$2"; shift 2 ;;
    --deleted)      DELETED_FILES="$2"; shift 2 ;;
    *) echo "[update-project-graph] Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$PROJECT_ROOT" ]]; then
  echo "[update-project-graph] --project-root is required" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"

# --- Helper: escape strings for Cypher ---
cypher_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\'/\\\'}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/}"
  printf '%s' "$s"
}

# Auto-derive project_id if not provided
if [[ -z "$PROJECT_ID" ]]; then
  PROJECT_ID=$(derive_project_id "$PROJECT_ROOT")
fi
# Escape project_id for safe Cypher embedding
PROJECT_ID="$(cypher_escape "$PROJECT_ID")"

if [[ -n "$COMPONENT" ]]; then
  COMPONENT_CYPHER="'$(cypher_escape "$COMPONENT")'"
else
  COMPONENT_CYPHER="null"
fi

echo "// ===================================="
echo "// Incremental Project Graph Update"
echo "// Generated by update-project-graph.sh"
echo "// Project: ${PROJECT_ROOT}"
echo "// Project ID: ${PROJECT_ID}"
echo "// Component: ${COMPONENT:-<none>}"
echo "// ===================================="
echo ""

# --- Delete removed files ---
if [[ -n "$DELETED_FILES" ]]; then
  echo "// --- Deleted Files ---"
  IFS=',' read -ra deleted_arr <<< "$DELETED_FILES"
  for file_path in "${deleted_arr[@]}"; do
    file_path=$(echo "$file_path" | xargs)  # trim whitespace
    [[ -z "$file_path" ]] && continue
    echo "MATCH (f:ProjectFile {path: '$(cypher_escape "$file_path")', project_id: '${PROJECT_ID}'}) DETACH DELETE f;"
    echo "MATCH (c:ProjectClass {file_path: '$(cypher_escape "$file_path")', project_id: '${PROJECT_ID}'}) DETACH DELETE c;"
    echo "MATCH (fn:ProjectFunction {file_path: '$(cypher_escape "$file_path")', project_id: '${PROJECT_ID}'}) DETACH DELETE fn;"
    echo "MATCH (ds:DocSection {file_path: '$(cypher_escape "$file_path")', project_id: '${PROJECT_ID}'}) DETACH DELETE ds;"
  done
  echo ""
fi

# --- Upsert changed files ---
if [[ -n "$CHANGED_FILES" ]]; then
  echo "// --- Changed Files ---"
  IFS=',' read -ra changed_arr <<< "$CHANGED_FILES"
  for file_path in "${changed_arr[@]}"; do
    file_path=$(echo "$file_path" | xargs)
    [[ -z "$file_path" ]] && continue
    local_path="${PROJECT_ROOT}/${file_path}"

    if [[ ! -f "$local_path" ]]; then
      continue
    fi

    local size mod_date lang
    size=$(wc -c < "$local_path" | xargs)
    mod_date=$(portable_file_date "$local_path")

    # Detect language from extension
    case "${file_path##*.}" in
      kt|kts) lang="kotlin" ;;
      java)   lang="java" ;;
      ts|tsx) lang="typescript" ;;
      js|jsx) lang="javascript" ;;
      py)     lang="python" ;;
      go)     lang="go" ;;
      rs)     lang="rust" ;;
      swift)  lang="swift" ;;
      c|h)    lang="c" ;;
      cpp|cc|cxx|hpp) lang="cpp" ;;
      cs)     lang="csharp" ;;
      rb)     lang="ruby" ;;
      php)    lang="php" ;;
      dart)   lang="dart" ;;
      ex|exs) lang="elixir" ;;
      scala)  lang="scala" ;;
      *)      lang="unknown" ;;
    esac

    echo "MERGE (f:ProjectFile {path: '$(cypher_escape "$file_path")', project_id: '${PROJECT_ID}'})"
    echo "SET f.language = '${lang}', f.size = ${size}, f.last_modified = '${mod_date}', f.component = ${COMPONENT_CYPHER};"
  done
  echo ""

  # Re-run symbol enrichment for changed files only
  if [[ -x "${PLUGIN_ROOT}/shared/graph/enrich-symbols.sh" ]]; then
    "${PLUGIN_ROOT}/shared/graph/enrich-symbols.sh" \
      --project-root "$PROJECT_ROOT" \
      --project-id "$PROJECT_ID" \
      --component "${COMPONENT:-}" \
      --files "$CHANGED_FILES" 2>/dev/null || true
  fi
fi
